app/lib/models.py
from .extensions import database
from flask_login import UserMixin

class User(UserMixin, database.Model):
    __tablename__ = 'user'

    id = database.Column(database.Integer, primary_key=True)
    user = database.Column(database.String(40), nullable=False, unique=True)
    password = database.Column(database.String(), nullable=False)
    salt_key = database.Column(database.String(), nullable=False)


class Craftyapi(database.Model):
    __tablename__ = 'craftyapi'

    id = database.Column(database.Integer, primary_key=True)
    url = database.Column(database.String(40), nullable=True)
    api_key = database.Column(database.String(40), nullable=True)
    server_id = database.Column(database.String(40), nullable=True)


class Infos(database.Model):
    __tablename__ = 'infos'

    id = database.Column(database.Integer, primary_key=True)
    server_java = database.Column(database.String(40), nullable=True)
    server_bedrock = database.Column(database.String(40), nullable=True)
    server_map = database.Column(database.String(40), nullable=True)
    discord_link = database.Column(database.String(40), nullable=True)

app/main.py
from os import chmod, environ
from flask import Flask
from flask_login import current_user
from lib.extensions import database, lm
from lib.utils import get_secret_key, get_database_path, create_default_database_register
from lib.api_consumer import check_api, get_server_name
from lib.models import User, Craftyapi, Infos
from lib.background_image import define_background_image
from routes.login import login_bp
from routes.logout import logout_bp
from routes.index import index_bp
from routes.server_log import server_log_bp
from routes.admin import admin_bp


def create_app(testing=False):
    app = Flask(__name__)
    app.register_blueprint(login_bp)
    app.register_blueprint(logout_bp)
    app.register_blueprint(index_bp)
    app.register_blueprint(server_log_bp)
    app.register_blueprint(admin_bp)
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{get_database_path('database.db', testing)}'
    app.secret_key = get_secret_key(testing)
    database.init_app(app)
    lm.init_app(app)
    lm.login_view = 'login'

    @lm.user_loader
    def user_loader(id):
        user = database.session.query(User).filter_by(id=id).first()
        return user
    
    @app.context_processor
    def inject_global_vars():
        i = database.session.query(Infos).filter_by(id=1).first()
        c = database.session.query(Craftyapi).filter_by(id=1).first()
        api_status = check_api(c.url, c.api_key, c.server_id)
        server_name=get_server_name(c.url, c.api_key, c.server_id)
        return dict(server_name=server_name,
                    server_map_url=i.server_map,
                    discord_link=i.discord_link,
                    api_status=api_status,
                    current_user=current_user
                    )
    return app

def production():
    app = create_app()
    with app.app_context():
        database.create_all()
        chmod(get_database_path('database.db'), 0o600)
        create_default_database_register(database)
    define_background_image()
    return app


if __name__ == "__main__":
    app = create_app()
    with app.app_context():
        database.create_all()
        chmod(get_database_path('database.db'), 0o600)
        create_default_database_register(database)
    from dotenv import load_dotenv
    from os import environ
    load_dotenv()
    define_background_image()
    app.run(debug=True, port=environ.get("PORT",5000))

app/routes/admin.py
from secrets import token_urlsafe
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import login_required

from lib.models import *
from lib.utils import password_to_hash


admin_bp = Blueprint('admin', __name__)

@admin_bp.route("/admin", methods=['GET', 'POST'])
@login_required
def admin():
    if request.method == 'POST':
        user = request.form['userForm']
        password = request.form['passwordForm']

        u = database.session.query(User).filter_by(id=1).first()
        if user:
            u.user = user
        if password:
            salt_key = token_urlsafe(64)
            u.salt_key = salt_key
            u.password = password_to_hash(password, salt_key)
        database.session.commit()

        craftyurl = request.form['craftyurlForm']
        craftyserverid = request.form['serverIdForm']
        craftyapi = request.form['craftyapiForm']
        

        c = database.session.query(Craftyapi).filter_by(id=1).first()
        c.url = craftyurl
        c.server_id = craftyserverid
        if craftyapi:
            c.api_key = craftyapi
        database.session.commit()

        server_java = request.form['JavaURLForm']
        server_bedrock = request.form['BedrockURLForm']
        server_map = request.form['MapURLForm']
        discord_link = request.form['DiscordLinkForm']

        i = database.session.query(Infos).filter_by(id=1).first()
        i.server_java = server_java
        i.server_bedrock = server_bedrock
        i.server_map = server_map
        i.discord_link = discord_link
        database.session.commit()
        return redirect((url_for('index.index')))
    
    if request.method == 'GET':
        u = database.session.query(User).filter_by(id=1).first()
        c = database.session.query(Craftyapi).filter_by(id=1).first()
        i = database.session.query(Infos).filter_by(id=1).first()
        data = dict(
                    user=u.user,

                    craftyurl=c.url,
                    craftyserverid=c.server_id,


                    server_java=i.server_java,
                    server_bedrock=i.server_bedrock,
                    server_map=i.server_map,
                    discord_link=i.discord_link)
        return render_template("admin.html", data=data)

app/routes/index.py
from flask import Blueprint, render_template
from lib.extensions import database
from lib.api_consumer import get_server_icon, get_server_status
from lib.models import *

index_bp = Blueprint('index', __name__)

@index_bp.route("/")
def index():
    c = database.session.query(Craftyapi).filter_by(id=1).first()
    i = database.session.query(Infos).filter_by(id=1).first()
    server_status = get_server_status(c.url, c.api_key, c.server_id)
    server_icon = get_server_icon(c.url, c.api_key, c.server_id)
    return render_template("index.html",
                           server_status=server_status,
                           server_uri_java=i.server_java,
                           server_uri_bedrock=i.server_bedrock,
                           server_icon=server_icon
                           )

app/routes/login.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import login_user
from lib.extensions import database
from lib.models import *
from lib.utils import password_to_hash


login_bp = Blueprint('login', __name__)

@login_bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        user = request.form['userForm']
        u = database.session.query(User).filter_by(id=1).first()
        password = password_to_hash(request.form['passwordForm'], u.salt_key)
        u = database.session.query(User).filter_by(user=user,password=password).first()
        if not u:
            return render_template("login.html", login_failed=True)
        login_user(u)
        return redirect((url_for('admin.admin')))
    if request.method == 'GET':
        return render_template("login.html")

app/routes/logout.py
from flask import Blueprint, redirect, url_for
from flask_login import login_required, logout_user



logout_bp = Blueprint('logout', __name__)

@logout_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect((url_for('index.index')))

app/routes/server_log.py
from flask import Blueprint, render_template
from lib.extensions import database
from lib.api_consumer import get_server_log
from lib.models import *

server_log_bp = Blueprint('server_log', __name__)

@server_log_bp.route("/serverlog")
def serverlog():
    c = database.session.query(Craftyapi).filter_by(id=1).first()
    server_log = get_server_log(c.url, c.api_key, c.server_id)
    
    return render_template("server_log.html",
                           server_log=server_log
                           )

app/templates/admin.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='style/admin.css') }}">
{% endblock %}

{% block title %}Admin{% endblock %}

{% block content %}
<h1>Info</h1>
<p class="api_status">Api Status: <span >{{ api_status }}</span></p><br>
<form action="" method="post">
    User: <input type="text" name="userForm" value="{{ data['user'] }}"><br>
    Password: <input type="password" name="passwordForm" value="" ><br>
    <br>
    Crafty URL: <input type="text" name="craftyurlForm" value="{{ data['craftyurl'] }}"><br>
    Crafty Server ID: <input type="text" name="serverIdForm" value="{{ data['craftyserverid'] }}"><br>
    Crafty API Token: <input type="password" name="craftyapiForm" value=""><br>
    <br>
    Java URL: <input type="text" name="JavaURLForm" value="{{ data['server_java'] }}"><br>
    Bedrock URL: <input type="text" name="BedrockURLForm" value="{{data ['server_bedrock'] }}"><br>
    Map URL: <input type="text" name="MapURLForm" value="{{ data['server_map'] }}"><br>
    Discord Link: <input type="text" name="DiscordLinkForm" value="{{data ['discord_link'] }}"><br>
    <input type="submit" value="Update">
</form>

{% endblock %}

{% block script %}
{% endblock %}

app/templates/base.html
<!doctype html>
<meta charset="UTF-8">
<head>
    <link href="https://fonts.cdnfonts.com/css/minecraft-3" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/base.css') }}">
    <title>{{ server_name }} | {% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
</head>

<body>
    <div class="background"></div>
    <div class="foreground">
        <nav class="navbar">
            <div class="nav-section left">
                <a href="{{ url_for('index.index') }}">{{ server_name }}</a>
                <div class="v-separator"></div>
                {% if server_map_url != "": %}
                    <a href="{{ server_map_url }}" target="_blank" rel="noopener noreferrer">Map</a>
                {% endif %}
                {% if api_status == 'Ok' %}
                    <a href="{{ url_for('server_log.serverlog') }}">Server Log</a>
                {% endif %}
                {% if discord_link != "": %}
                    <a href="{{ discord_link }}">Discord</a>
                {% endif %}
            </div>
            <div class="nav-section right">
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('admin.admin') }}">Admin</a>
                    <a href="{{ url_for('logout.logout') }}">Logout</a>
                {% else %}
                    <a href="{{ url_for('login.login') }}">Login</a>
                {% endif %}
            </div>
        </nav>
        <div class="h-separator"></div>
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>
    {% block script %}{% endblock %}
</body>

app/templates/index.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='style/index.css') }}">
{% endblock %}

{% block title %}Home Page{% endblock %}

{% block content %}
<div class="server_info">
    {% if server_status['running'] == 'true' %}
        {% if server_icon == "Ok": %}
            <img src="{{ url_for('static', filename='img/server-icon.png') }}" width="64" height="64">
        {% endif %}
        <p class="motd">{{ server_status['motd'] }}</p>
    {% endif %}
</div>
<div class="server_url">
    <h2 >Java: <span onclick="copyLink('{{ server_uri_java }}')" class="server-link">{{ server_uri_java }}</span></h2>
    {% if server_uri_bedrock != "": %}
        <h2>Bedrock: <span onclick="copyLink('{{ server_uri_bedrock }}')" class="server-link">{{ server_uri_bedrock }}</span></h2>
    {% endif %}
</div>
<div class="server_status">
    {% if api_status == 'Ok' %}    
        {% if server_status['running'] == 'true' %}
            <h3 class="online">Online</h3>
        {% else %}
            <h3 class="offline">Offline</h3>
        {% endif %}
        <h3>Players: {{ server_status['players_online'] }}</h3>
        {% if server_status['players_online'] > 0 %}
            <h3 class="Players_Online">Players Online:</h3>
            <ul>
            {%for i in server_status['players']%}
                <li>{{ i }}</li>
            {%endfor%}
            </ul>
        {% endif %}
    {% endif %}
</div>
{% endblock %}

{% block script %}
<script>
    function copyLink(text) {
        var elem = document.createElement("textarea");
        document.body.appendChild(elem);
        elem.value = text;
        elem.select();
        document.execCommand("copy");
        alert("Copiado link " + text);
        document.body.removeChild(elem);
    }
</script>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='style/login.css') }}">
{% endblock %}

{% block title %}Login{% endblock %}

{% block content %}
<h1>Login</h1>
<form action="" method="post">
    User: <input type="text" name="userForm"><br>
    Password: <input type="password" name="passwordForm"><br>
    <input type="submit" value="Login">
</form>
{% if login_failed %}
    <p class="login_failed">Login failed, incorrect username or password</p>
{% endif %}

{% endblock %}

{% block script %}
{% endblock %}

app/templates/server_log.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='style/server_log.css') }}">
{% endblock %}

{% block title %}Server Log{% endblock %}

{% block content %}
<div id="server_log">
{% if api_status !=  "Ok": %}
    <p>{{ server_log }}</p>
{% else %}
    {%for i in server_log[1:-1]%}
        {% if i[-1] ==  ",": %}
            <p>{{i[1:-2]}}</p>
        {% else %}
            <p>{{i[1:-1]}}</p>
        {% endif %}
    {%endfor%}
{% endif %}
</div>
{% endblock %}

{% block script %}
<script>
let elem = document.getElementById('server_log');
elem.scrollTop = elem.scrollHeight;
</script>
{% endblock %}